no config mounts

diff --git a/concourse/resources/dockerSwarm/resource/out b/concourse/resources/dockerSwarm/resource/out
--- a/concourse/resources/dockerSwarm/resource/out
+++ b/concourse/resources/dockerSwarm/resource/out
@@ -8,8 +8,6 @@ buffer=$(cat)
 #Extract variables from json
 serviceName=$(echo $buffer | jq -r '.source.serviceName')
 repository=$(echo $buffer | jq -r '.source.repository')
-executableName=$(echo $buffer | jq -r '.source.executableName')
-nodeName=$(echo $buffer | jq -r '.source.nodeName')
 portNumber=$(echo $buffer | jq -r '.source.portNumber')
 network=$(echo $buffer | jq -r '.source.network')
 swarmMaster=$(echo $buffer | jq -r '.source.swarmMaster')
@@ -19,7 +17,6 @@ export DOCKER_HOST="${swarmMaster}"
 echo --- SERVICE INFO ---
 echo serviceName: ${serviceName}
 echo repository: ${repository}
-echo executableName: ${executableName}
 echo portNumber: ${portNumber}
 echo network: ${network}
 echo swarmMaster: ${swarmMaster}
@@ -34,27 +31,57 @@ docker service rm ${serviceName}
 
 docker pull ${repository}
 
-# This treats all nodes the same, so it is necessarily a superset
-# The extra volume mounts are harmless, if annoying
-if [ -n "${portNumber%null}" ]; then
+#
+# The nodes do not have the same command line.
+# Some need secrets on the boxes mounted into the images, some publish a port, others do neither.
+# It's longer but clearer to just do them individually.
+#
+
+if [ ${serviceName} = "auth" ]; then
 
     docker service create \
         --name=${serviceName} \
-        --publish ${portNumber}:8080 \
         --network=${network} \
-        --mount type=bind,source=/home/ubuntu/${executableName}.exe.config,target=/service/${executableName}.exe.config \
-        --mount type=bind,source=/home/ubuntu/${executableName}.exe.secrets,target=/service/${executableName}.exe.secrets \
+        --publish ${portNumber}:8080 \
+        --mount type=bind,source=/home/ubuntu/Auth.exe.secrets,target=/service/Auth.exe.secrets \
         --mount type=bind,source=/home/ubuntu/AuthCertificate.pfx,target=/AuthCertificate.pfx \
         ${repository}
+
+elif [ ${serviceName} = "comms" ]; then
+
+    docker service create \
+        --name=${serviceName} \
+        --network=${network} \
+        --mount type=bind,source=/home/ubuntu/Comms.exe.secrets,target=/service/Comms.exe.secrets \
+        ${repository}
+
+elif [ ${serviceName} = "sessions" ]; then
+
+    docker service create \
+        --name=${serviceName} \
+        --network=${network} \
+        ${repository}
+
+elif [ ${serviceName} = "gateway" ]; then
+
+    docker service create \
+        --name=${serviceName} \
+        --network=${network} \
+        --publish ${portNumber}:8080 \
+        ${repository}
+
+elif [ ${serviceName} = "frontend" ]; then
+
+    docker service create \
+        --name=${serviceName} \
+        --network=${network} \
+        --publish ${portNumber}:8080 \
+        ${repository}
+
 else
 
-    docker service create \
-        --name=${serviceName} \
-        --network=${network} \
-        --mount type=bind,source=/home/ubuntu/${executableName}.exe.config,target=/service/${executableName}.exe.config \
-        --mount type=bind,source=/home/ubuntu/${executableName}.exe.secrets,target=/service/${executableName}.exe.secrets \
-        --mount type=bind,source=/home/ubuntu/AuthCertificate.pfx,target=/AuthCertificate.pfx \
-        ${repository}
+    echo "ERROR: Unknown microservice"
+    exit 1
 fi
 
 echo '{ "version": { "ref": "'$BUILD_ID'" } }' >&3
